module:
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geofield: 0
  geophp: 0
  help: 0
  history: 0
  image: 0
  jssor: 0
  kint: 0
  leaflet: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_geojson: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  classy: 0
  bartik: 0
  seven: 0
  mappy: 0
