name: Config Filter
type: module
description: Config Filter allows other modules to interact with a ConfigStorage through filter plugins.
# core: 8.x
package: Config

# Information added by Drupal.org packaging script on 2018-11-14
version: '8.x-1.4'
core: '8.x'
project: 'config_filter'
datestamp: 1542184984
