source "https://rubygems.org"

gem 'compass'
gem 'sass'
gem 'sass-globbing'  # Import Sass files based on globbing pattern.
gem 'bourbon'        # Import Bourbon SASS framework.
gem 'neat'           # Import Bourbon Neat grid framework
