check:
  disabled_extensions: false
  interval_days: 7
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - m3j1j7n0k8o9u7r3@savaslabs.slack.com
  threshold: security
_core:
  default_config_hash: 2QzULf0zovJQx3J06Y9rufzzfi-CY2CTTlEfJJh2Qyw
