views.display_extender.simple_sitemap_display_extender:
  type: views_display_extender
  mapping:
    index:
      label: 'Index'
      type: boolean
    variant:
      label: 'Sitemap variant'
      type: string
    priority:
      label: 'Priority'
      type: string
    changefreq:
      label: 'Change frequency'
      type: string
    arguments:
      label: 'Indexed arguments'
      type: sequence
      sequence:
        type: string
    max_links:
      label: 'Max links'
      type: integer
